spring.application.name=itinerary-service

# JPA — let Hibernate auto-create/update tables in the 'itinerary' schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=itinerary

# gRPC Client Configuration
grpc.client.location-service.address=${GRPC_CLIENT_LOCATION_SERVICE_ADDRESS}
grpc.client.location-service.negotiationType=${GRPC_CLIENT_LOCATION_SERVICE_NEGOTIATION_TYPE}
