spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          # Here we use the actual docker container name and let Docker resolve the internet mapping itself
          routes:
            - id: auth-service
              uri: http://auth-service:8002
              predicates:
                - Path=/auth/**
            - id: user-service
              uri: http://user-service:8001
              predicates:
                - Path=/users/**
            - id: itinerary-service
              uri: http://itinerary-service:8004
              predicates:
                - Path=/itineraries/**
            - id: expense-service
              uri: http://expense-service:8003
              predicates:
                - Path=/expenses/**
            - id: location-service
              uri: http://location-service:8005
              predicates:
                - Path=/locations/**
            - id: notification-service
              uri: http://notification-service:8006
              predicates:
                - Path=/notifications/**

server:
  port: 8000

jwt:
  secret: ${JWT_SECRET}logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] - %msg%n'
