#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
  -- API gateway
  CREATE ROLE ${GATEWAY_DB_USER} LOGIN PASSWORD '${GATEWAY_DB_PASSWORD}';
  CREATE SCHEMA gateway AUTHORIZATION ${GATEWAY_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA gateway TO ${GATEWAY_DB_USER};

  -- Auth service
  CREATE ROLE ${AUTH_DB_USER} LOGIN PASSWORD '${AUTH_DB_PASSWORD}';
  CREATE SCHEMA auth AUTHORIZATION ${AUTH_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA auth TO ${AUTH_DB_USER};

  -- User service
  CREATE ROLE ${USER_DB_USER} LOGIN PASSWORD '${USER_DB_PASSWORD}';
  CREATE SCHEMA app_user AUTHORIZATION ${USER_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA app_user TO ${USER_DB_USER};

  -- Expense service
  CREATE ROLE ${EXPENSE_DB_USER} LOGIN PASSWORD '${EXPENSE_DB_PASSWORD}';
  CREATE SCHEMA expense AUTHORIZATION ${EXPENSE_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA expense TO ${EXPENSE_DB_USER};

  -- Itinerary service
  CREATE ROLE ${ITINERARY_DB_USER} LOGIN PASSWORD '${ITINERARY_DB_PASSWORD}';
  CREATE SCHEMA itinerary AUTHORIZATION ${ITINERARY_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA itinerary TO ${ITINERARY_DB_USER};

  -- Location service
  CREATE ROLE ${LOCATION_DB_USER} LOGIN PASSWORD '${LOCATION_DB_PASSWORD}';
  CREATE SCHEMA location AUTHORIZATION ${LOCATION_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA location TO ${LOCATION_DB_USER};

  -- Notification service
  CREATE ROLE ${NOTIFICATION_DB_USER} LOGIN PASSWORD '${NOTIFICATION_DB_PASSWORD}';
  CREATE SCHEMA notification AUTHORIZATION ${NOTIFICATION_DB_USER};
  GRANT USAGE, CREATE ON SCHEMA notification TO ${NOTIFICATION_DB_USER};

  -- Restrict public schema access
  REVOKE ALL ON SCHEMA public FROM PUBLIC;
SQL
